### ISSUE TITLE
DEB repo: package list refresh fails, error 402 (payment required)

### ISSUE THREAD

**Issue by prinkpan** [caddyserver/dist#100]
Receiving the following error while trying `sudo apt update` on debian.

```
E: Failed to fetch https://dl.cloudsmith.io/public/caddy/stable/deb/debian/dists/any-version/InRelease  402  Payment Required [IP: 18.67.39.68 443]
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is no longer signed.
```

**Comment by francislavoie** [comment]
Welp :grimacing:

![image](https://github.com/caddyserver/dist/assets/2111701/700c14d1-1b70-46d9-ab55-5c5663729f46)

FYI @lskillen, anything you can do to help us with this? Not much we can do to prevent Caddy's growth.

**Comment by BartoszBlizniak** [comment]
Hey @prinkpan / @francislavoie  - Bart from Cloudsmith here, we have doubled your current OSS Bandwidth to help your users pull packages!

**Comment by francislavoie** [comment]
Thank you!

**Comment by lskillen** [comment]
You're welcome! Happy to support Caddy. 😁 

![caddybw](https://github.com/caddyserver/dist/assets/2248287/68f5b058-90ce-47ab-b344-704419ee946e)

**Comment by mholt** [comment]
@lskillen @BartoszBlizniak  Ah you guys are amazing. Thanks so much.
