### ISSUE TITLE
402 Payment Required from cloudsmith

### ISSUE THREAD

**Issue by roman-belkov** [caddyserver/dist#115]
Previously discussed here: https://github.com/caddyserver/dist/issues/114

`E: Failed to fetch https://dl.cloudsmith.io/public/caddy/stable/deb/debian/dists/any-version/InRelease  402  Payment Required`

This blocks updates & upgrades on machines.

It appears that all bandwidth is gone in only 5 days.

**Comment by mstaack** [comment]
yeah same for me...
`Err:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease
  402  Payment Required [IP: 2600:9000:275b:ea00:* 443]`

**Comment by zieddhf** [comment]
+1

**Comment by myazaki** [comment]
same here, never get into this before.

**Comment by nicolinuxfr** [comment]
Same here this morning.

**Comment by iorimoe** [comment]
same

**Comment by mohammed90** [comment]
It's strange that we've hit our 2TB bandwidth quota in merely 3 days. Our apt repo appears to be abused as part of CI builds. If any of you are using the apt package in CI, please change your approach.

Until then, we're working on a solution.

N.B. Please refrain from making more comments of "me too" unless you're adding more details or context.

**Comment by ob6160** [comment]
If it helps anybody, we had success using the following to install Caddy:

```
# Define Caddy version and URL for the binary and checksum
CADDY_VERSION="2.7.6"
CADDY_URL="https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz"
CHECKSUM_URL="https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_checksums.txt"

# Download Caddy and checksum files
curl -sOL ${CADDY_URL}
curl -sOL ${CHECKSUM_URL}

# Verify checksum
grep " caddy_${CADDY_VERSION}_linux_amd64.tar.gz$" caddy_${CADDY_VERSION}_checksums.txt | shasum -c

# Extract Caddy binary
tar xzf caddy_${CADDY_VERSION}_linux_amd64.tar.gz caddy

# Move Caddy to the PATH
sudo mv caddy /usr/local/bin/

# Verify installation
caddy version
```

There might be room for improvement with the script of course, but it got us up and running again in our pipeline (sorry for using the apt repo originally!!)

**Comment by andris9** [comment]
I gave up using Cloudsmith and started to install from releases directly (Ubuntu 22.04)

```bash
CADDY_VERSION="2.7.6"
CADDY_ARCH="amd64"

wget -q "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_${CADDY_ARCH}.deb"
apt install "./caddy_${CADDY_VERSION}_linux_${CADDY_ARCH}.deb"
```

**Comment by francislavoie** [comment]
This is due to abusive users hammering Cloudsmith. There's absolutely no way we received 2.5TB of legitimate traffic within 3 days. For the record, here's our usage tracking for the past year:

![image](https://github.com/caddyserver/dist/assets/2111701/9e4864f9-b01e-410d-ae8d-79039e80a909)

/cc @lskillen @BartoszBlizniak from CloudSmith

**Comment by mholt** [comment]
We're also going to ask that anyone using the Cloudsmith repos in CI to use [xcaddy](https://github.com/caddyserver/xcaddy) instead.

**Comment by bakerds** [comment]
> It's strange that we've hit our 2TB bandwidth quota in merely 3 days

There are many public mirrors that would host your repository for free, with no bandwidth limits. Have you considered a distributed approach?

**Comment by mohammed90** [comment]
> > It's strange that we've hit our 2TB bandwidth quota in merely 3 days
> 
> There are many public mirrors that would host your repository for free, with no bandwidth limits. Have you considered a distributed approach?

Can you elaborate?

**Comment by bakerds** [comment]
> > > It's strange that we've hit our 2TB bandwidth quota in merely 3 days
> > 
> > 
> > There are many public mirrors that would host your repository for free, with no bandwidth limits. Have you considered a distributed approach?
> 
> Can you elaborate?

For example, the many organizations listed [here](https://launchpad.net/ubuntu/+archivemirrors) or [here](https://mirrors.rockylinux.org/mirrormanager/mirrors) provide their services for free, and would very likely be happy to host your repo as well. Then you just need to refer users to a nearby healthy mirror.

**Comment by compuguy** [comment]
> We're also going to ask that anyone using the Cloudsmith repos in CI to use [xcaddy](https://github.com/caddyserver/xcaddy) instead.

That's not a 1:1 replacement for a Debian/Ubuntu APT repository. It looks like you're using Fedora's COPR for the RHEL/Fedora. Maybe someone should move Debian/deb repo to an Ubuntu PPA @mholt?
https://caddyserver.com/docs/install#fedora-redhat-centos
https://launchpad.net/ubuntu/+ppas

**Comment by francislavoie** [comment]
@compuguy the best solution we can offer for now is that you download the `.deb` from our Github releases (which is what we upload to Cloudsmith anyway).

We're still waiting for communication from Cloudsmith about this.

**Comment by andyshinn** [comment]
Talk to Fastly. They can front the Cloudsmith repo as a CDN. It was something I worked with them on for the Alpine Linux package CDN.

**Comment by mholt** [comment]
(Following this discussion closely but am traveling through the end of the week and will get to this when I have a chance)

**Comment by BartoszBlizniak** [comment]
Hey everyone 👋 

@francislavoie - I've increased the limit once more to get everyone unblocked. I'm also going to take some time to look at our logs to determine where the majority of requests are coming from.

**Comment by BartoszBlizniak** [comment]
Hey @francislavoie - I will reach out via email so we can continue the conversation via our support portal. For the wider audience, we have currently increased the bandwidth to 5TB while we address the bandwidth usage.

**Comment by mholt** [comment]
Hey @BartoszBlizniak , thank you, although I have fleet been emailing Glenn and asked that the limit not be increased any further. We have already utilized much of your generosity and do not want to take advantage of that while we look into mirrors and such.

**Comment by mholt** [comment]
Cloudsmith has notified me that they have implemented measures, so we appreciate their help and cooperation :smiley:
