### ISSUE TITLE
Copr repo stuck at v2.8.1

### ISSUE THREAD

**Issue by mundry** [caddyserver/dist#122]
Hi,

the Copr repo for RPM-based distros is still at version 2.8.1 of Caddy.

Will there be a rebuild to get the latest version soon?

Cheers

**Comment by carlwgeorge** [comment]
Sorry for the lag.  We've completed the 2.8.4 build in copr now.

https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/7711857/
