### ISSUE TITLE
Deb package for Debian/Ubuntu based distros

### ISSUE THREAD

**Issue by balki** [caddyserver/dist#21]
Ubuntu/Debian is the default OS in many VPS providers. It is nice to have a deb package for easy installation and keeping up to date. (Disclaimer: I am not familiar with debian packaging).

**Comment by mholt** [comment]
Yeah, we'd love to see this too. Anyone know how to make one? Ideally we want: `apt install caddy`.

**Comment by francislavoie** [comment]
This is almost done: https://github.com/caddyserver/caddy/pull/3280

This repo now has scripts that are part of the `.deb` https://github.com/caddyserver/dist/tree/master/scripts

**Comment by francislavoie** [comment]
This is done as of last week, and the latest 2.0.0 stable version is now offered via a gemfury APT repo.

**Comment by balki** [comment]
It took me some time to figure out how to install from gemfury. I will leave it below

    root@c5e9554bfd33:/# apt install ca-certificates
    root@c5e9554bfd33:/# cat > /etc/apt/sources.list.d/fury.list
    deb [trusted=yes] https://repo.fury.io/caddy/ /
    root@c5e9554bfd33:/# apt update
    root@c5e9554bfd33:/# apt install caddy

Project url: https://gemfury.com/caddy/deb:caddy
About installing: https://gemfury.com/help/apt-repository#apt-setup

**Comment by francislavoie** [comment]
The instructions are right here:

https://caddyserver.com/docs/install#debian-ubuntu-raspbian

**Comment by drcongo** [comment]
Sorry to comment in a closed thread, but I've got a couple of issues with the gemfury installation.

1. It installed a zero byte Caddy binary at `/usr/local/bin/caddy`
2. It installs a service file pointing to `/usr/bin/caddy`

The second one is not much of a problem, I can just overwrite the service file. But I'm not sure how to get around the first one, @francislavoie any ideas?

**Comment by francislavoie** [comment]
@drcongo I have no idea how that could've happened. I see no mention in the .deb of `/usr/local/bin`. Could you please post a thread on the forums with as much detail as possible so we can investigate further? This is the first I've heard of an issue like this.

https://caddy.community

**Comment by drcongo** [comment]
I was writing an Ansible role to install Caddy when this happened, and since switched the role to just install with a binary from GitHub. Once I've got my head around the new Caddyfile I'll see if I can reproduce it on a clean server and start a thread over on the forums if so. Thanks.
