### ISSUE TITLE
Use the service file in the `init/` dir for arch

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/dist#22]
@shibumi I noticed that the `caddy.service` file in the `archlinux/` dir is outdated compared to the one in `init/`.

Could we update this line to reference the `init/` one like `../init/caddy.service`?

https://github.com/caddyserver/dist/blob/master/archlinux/PKGBUILD#L17

See https://github.com/caddyserver/dist/pull/16 where we discussed the changes to the service files.

Also as an aside, we need an RC3 build! 😉

**Comment by shibumi** [comment]
Hi, this are great news, I will include them in the next release.

**Comment by shibumi** [comment]
@mholt can you assign this issue to me?

**Comment by francislavoie** [comment]
Arch files are removed as per the discussion in https://github.com/caddyserver/dist/pull/58, so I'll close this.
