### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by carlwgeorge** [caddyserver/dist#29]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.9

### 2. What are you trying to do?
`man caddy`

Having a man page available would be useful for quick reference on servers and would help comply with distro packaging guidelines.

**Comment by pymnh** [comment]
I will look into writing manpages, at least for cli-usage but ideally for also for config/caddyfile.

**Comment by pymnh** [comment]
> Dunno if this'll help: https://godoc.org/within.website/x/internal/manpage

Very useful. thanks

Small update on this:
I went on adding a `man` subcommand, like this:
```
	RegisterCommand(Command{
		Name:  "man",
		Func:  cmdMan,
		Usage: "[--force]",
		Short: "Print manual pages for Caddy",
                Long: `
Prints manual pages for Caddy and its available subcommands into current directory. In case --force flag
ist set, existing man pages will be overwritten.`,
	})
```

`cmdMan` then itereates through `commands` and the main command and generates templates. Mostly works as intended, but I'm a total newbie to Go and need to familiarize myself with coding style and error handling before I submit a PR. 

Is the general direction alright?

**Comment by mholt** [comment]
That sounds like a good approach, yeah. I don't know much about generating man pages, but I suppose that's as good a way as any to do it.

Am trying to decide if this will be used enough to merit inclusion into the standard Caddy distribution or if it should be a third party plugin.

**Comment by pymnh** [comment]
> Am trying to decide if this will be used enough to merit inclusion into the standard Caddy distribution or if it should be a third party plugin.

Makes sense, target users for this feature would be distribution maintainers only.

I have [opened a PR](caddyserver/caddy#4316) with my current draft, I guess it should work out to rewrite it as module. Just let me know

**Comment by mholt** [comment]
Good point, so yeah, probably an external module.

**Comment by francislavoie** [comment]
I'll close this, because both the .deb and .rpm have the manpage bundled, via the `caddy manpage` command which can generate it. See https://github.com/caddyserver/dist/commit/e06ce615e2da93a5908ca9978a1f992b6fbe2ab5 for example.
