### ISSUE TITLE
Caddy 2 Installation Command Install RC3

### ISSUE THREAD

**Issue by bestpaydeals** [caddyserver/dist#31]
Hi, I used the following command on CentOS 7 to install Caddy 2:
yum install yum-plugin-copr
yum copr enable @caddy/caddy
yum install caddy

But, after installation it said RC3 installed.
So, how do I install the stable version?

**Comment by mholt** [comment]
I believe @carlwgeorge will update it to the v2 release when he has a chance :)

**Comment by francislavoie** [comment]
> Besides, can I get Caddy 2 Caddyfile sample configuration for WordPress? The old one didn't work!

Check out the forums https://caddy.community, that question has been asked a few times! Make sure to sort by most recent to avoid finding posts for Caddy v1.

**Comment by bestpaydeals** [comment]
@carlwgeorge please update that to v2 stable. Thanks.

**Comment by Conan-Kudo** [comment]
It's in the process of being built...

**Comment by Conan-Kudo** [comment]
This is now fixed and Caddy 2.0.0 final is available for CentOS 7+ and Fedora 31+.

**Comment by mholt** [comment]
You guys are awesome! Thanks @Conan-Kudo !
