### ISSUE TITLE
Add MIPS arch build target to release pipeline

### ISSUE THREAD

**Issue by GalacticLion7** [caddyserver/dist#37]
Something like `opkg install caddy` would be really great.

**Comment by GalacticLion7** [comment]
Considering the fact that routers use various different architectures, can Caddy can work with any `GOARCH` architecture?

**Comment by francislavoie** [comment]
We build Caddy releases for a pretty big range of arches, you can find them here: https://github.com/caddyserver/caddy/releases (expand the Assets section)

It might work on other arches, but we can't guarantee support because we don't build for them.

**Comment by mholt** [comment]
@GalacticLion7 Would you be willing to maintain the package? If so, let us know what you need and we'll be happy to have it. Otherwise, I guess I'll close the issue... (no one on our team I'm aware of uses Caddy with OpenWrt)

**Comment by GalacticLion7** [comment]
@mholt sure, this is what I was intending. All I need are official releases of Caddy for the MIPS arches on Linux.

**Comment by mholt** [comment]
@GalacticLion7 Ah I see, yeah that would be great if you could. @francislavoie It should be pretty easy to add mips to our build targets right?

**Comment by francislavoie** [comment]
Yeah I think so. I think we can do that before the next release. I'll try the cross-build locally real quick to make sure it at least produces a binary.

**Comment by francislavoie** [comment]
@GalacticLion7 Do you know which of those arches you need? ☝️

**Comment by francislavoie** [comment]
I'll close this as inactive.
