### ISSUE TITLE
GPG signed releases - reconsider gemfury?

### ISSUE THREAD

**Issue by Addvilz** [caddyserver/dist#42]
Current official DEB repo does not provide GPG signed releases file, making it impossible to verify the authenticity of the repository. It seems that gemfury has no support for GPG signed releases file at all, so perhaps it would make sense to consider another provider - as this is a pretty essential thing to have?

There are certainly plenty of options to choose from. I have previously used Cloudsmith and it seems to be working just fine - @lskillen can perhaps pitch in here, I am not sure if a project of this size is something they can take on policy-wise.

**Comment by francislavoie** [comment]
We considered our options and went with Gemfury because they gave us good support and GPG signing is marked as an upcoming feature. I'd rather wait for them to implement it than switch.

I also think that GPG signing is not that much of a concern right now, the attack surface is pretty low. No matter what, you would still need to trust that the Caddy project produced good binaries. GPG doesn't really aid with that.

**Comment by Addvilz** [comment]
> GPG doesn't really aid with that.

Correct. But it does help to ensure that nothing in between me and the publisher repo is compromised and it is actually you who published these packages - at the very least someone who has access to the repo. Consider that APT repos are not always accessed directly from publisher repo, they are also often mirrored locally, there are intermediate caches and all kinds of interesting bits in between.

> GPG signing is marked as an upcoming feature

... and as far as I am aware, it has been marked as an upcoming feature for what, 5 years now? I am not trying to say anything here, since I have no clue what their plans regarding the GPG implementation are, or if there is any progress regarding this.

Don't get me wrong, this is a nice to have. I personally have means to have the .deb retrieved directly from github releases and be included in a signed local mirror, but having a signed upstream would be much cleaner and nicer to manage.

**Comment by francislavoie** [comment]
> But it does help to ensure that nothing in between me and the publisher repo is compromised and it is actually you who published these packages

Gemfury uses HTTPS so tampering is much more difficult.

> Consider that APT repos are not always accessed directly from publisher repo, they are also often mirrored locally, there are intermediate caches and all kinds of interesting bits in between.

True, but that's not really under our control. You need to trust the caches used as well.

> ... and as far as I am aware, it has been marked as an upcoming feature for what, 5 years now?

😬 🤷‍♂️

Anyways I'll just say this is low priority because there are better uses of our time since we have a solution that works.

**Comment by Addvilz** [comment]
Just to clarify that.

> True, but that's not really under our control. You need to trust the caches used as well.

That's the thing, you don't need to trust the cache/mirror. You only need to have your GPG key present locally to ensure the repo comes from upstream. Mirrors basically serve as static proxies. They do not re-sign packages (or repos in this case), they only serve and mirror files you already have signed. Thus it might as well be evil hackzorz mirroring the repo, there is not much they could do around modifying your repo once it is already signed.

**Comment by lskillen** [comment]
Hey folks! I didn't want to stomp in here if @francislavoie and co are using Gemfury, and happy with it; but just wanted to say that yes, we calculate checksums and signatures for _all_ packages that pass through @cloudsmith-io. I think in the case of Ruby, what we don't do is actually embed the new signature in the gem, but if that was of interest of anyone we'd be happy to do it as a matter of priority. Glad to hear we're not the only ones with great support though! 😄

**Comment by Conan-Kudo** [comment]
> That's the thing, you don't need to trust the cache/mirror. You only need to have your GPG key present locally to ensure the repo comes from upstream. Mirrors basically serve as static proxies. They do not re-sign packages (or repos in this case), they only serve and mirror files you already have signed.

This is not generally true for Debian repository mirrors with tools like `reprepro` and `aptly`. Metadata is not preserved and is fully regenerated by the tool itself, and the repository metadata is obviously resigned with your local key.

**Comment by Addvilz** [comment]
I can not attest to all the possible configurations of all the mirrors and all the mirroring solutions out there, but I do not believe that what you suggest is the general case except for select use cases ex. private multi-mirrors of several upstreams, partial mirrors etc. 

The reason behind that is that if every mirror and caching proxy would discard and regenerate metadata, you would have to distribute, maintain and protect signing keys of every intermediate and distribute subsequent public keys to every host using those intermediates. For most cases, doing so is simply unnecessary overhead. Unless you want to merge multiple repos (??? why) or have private packages mixed in with mirrored packages (??? again, why), a transparent caching HTTP proxy serves perfectly well to mirror a remote repo. And that is what I see used for the most part in deployments like this.

Regardless, we can have this argument either way for days. I still think signing repos is a good thing, and a necessary one. Whether Caddy members want to implement this, well that's up to them.

**Comment by Conan-Kudo** [comment]
> Regardless, we can have this argument either way for days. I still think signing repos is a good thing, and a necessary one. Whether Caddy members want to implement this, well that's up to them.

I do not disagree with you, I'm just pointing out that people who use `aptly` or `reprepro` for automatic mirroring also automatically lose any upstream repo guarantees.

**Comment by francislavoie** [comment]
Closing in favour of #49 where this will be resolved. We'll continue to publish our .deb to Gemfury for the forseeable future (there's no harm to do so) but we'll now also publish to Cloudsmith which gives us some nice extra features, including GPG signing.

**Comment by Addvilz** [comment]
Niiice, thanks @francislavoie and @lskillen!
