### ISSUE TITLE
Why user/group 'caddy' instead of standard 'www-data' in Debian package?

### ISSUE THREAD

**Issue by jotteerr** [caddyserver/dist#47]
Hi,

all webservers on debian systems (at least from official repositories) are running as user 'www-data'. In the Caddy Debian package it's 'caddy', per systemd service file.

IMO it would be better to adhere to Debian standards, if only to make it easier to switch from/to another webserver. F. ex. as a former nginx user, all my web pages are owned by www-data. Of course it's no much work to chown to user caddy, but inconvenient anyway.

Joachim

**Comment by francislavoie** [comment]
The debian package adds the Caddy user to the www-data group so it shouldn't be an issue.

The reason is more for isolation of secrets, basically, since the `caddy` user manages certs and keys.

**Comment by francislavoie** [comment]
I'll close this as answered.
