### ISSUE TITLE
Ubuntu repository from Documentation don't work anymore

### ISSUE THREAD

**Issue by kozicpetar** [caddyserver/dist#48]
I used repository from documentation for installation of Caddy.

```
echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" \
    | sudo tee -a /etc/apt/sources.list.d/caddy-fury.list
sudo apt update
sudo apt install caddy
```
from this page:
https://caddyserver.com/docs/download

but now `apt update` ignore everything about that repo.
Also, if I try to open `https://apt.fury.io` looks down?

Some other repo or info?
Thank you.

**Comment by francislavoie** [comment]
https://apt.fury.io is not meant to be accessible in a browser.

Did you upgrade Ubuntu to 20.10 recently? Whenever you upgrade, Ubuntu usually  disables all existing unofficial package sources just to be safe. You'll need to manually re-enable them.

To do that, go look in the files in `/etc/apt/sources.list.d` and check that they weren't commented out with a leading `#`. If they were, remove that `#`, save, and try `apt update` again.

**Comment by kozicpetar** [comment]
Hi @francislavoie,
thanks on answer.

No, that is Ubuntu 18.04, not upgraded.

**Comment by kozicpetar** [comment]
> https://apt.fury.io is not meant to be accessible in a browser. That's working as expected.

Ok, than problem is on my side. Thank you.
