### ISSUE TITLE
Script to package .deb

### ISSUE THREAD

**Issue by Xinayder** [caddyserver/dist#50]
Would it be possible to have in this repo the script that creates the `.deb` package?

I want to provide a custom Caddy build with plugins and update my installation on my server with the package instead of having to do it manually.

**Comment by francislavoie** [comment]
We use [goreleaser](https://github.com/goreleaser/goreleaser) for this:

https://github.com/caddyserver/caddy/blob/master/.goreleaser.yml#L71

The only thing that changes in the `.deb` between releases really, is the `caddy` binary itself. You could just pin the `.deb` to some specific version, then just replace the `caddy` binary at `/usr/bin/caddy` on your system whenever you need to.

We'll eventually ship `xcaddy` via a `.deb` repo as well, we just haven't gotten around to doing it yet.
