### ISSUE TITLE
FYI: Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [caddyserver/dist#51]
I created automatic chocolaty package which follows your releases.

* https://chocolatey.org/packages/caddy

I will continue maintaining the package as I already have infrastructure for that job setup. The code for the package is [here](https://github.com/majkinetor/au-packages/tree/master/caddy). 

As a stable package with complete version history, you might want to mention it in the install options.

If you need me to change anything, rise a ticket on repository mentioned above.

**Comment by mholt** [comment]
Awesome, thanks for maintaining this!

I'll update our docs to include this. :+1:

If you think it'd be helpful to be in our developer Slack (we have a handful of distro/pkg maintainers and a channel dedicated to distribution), let me know which email to send an invite to.
