### ISSUE TITLE
Unable to SFTP into server

### ISSUE THREAD

**Issue by NetOperatorWibby** [caddyserver/dist#53]
My experience is primarily with nginx but I'm trying out Caddy for a new project. For some reason, I am unable to SFTP into my server.

For reference, I'm using DigitalOcean and I initiated the server with my SSH credentials.

**Comment by Mohammed90** [comment]
The hardening we implement disables SFTP by default. We can enable it by adding `sftp_enabled: true` here:
https://github.com/caddyserver/dist/blob/e784a6dd41d1cd4f72de2a427961bfb097b72cf9/packer/ansible/ansible-playbook.yml#L6-L15

**Comment by NetOperatorWibby** [comment]
There's nothing I can put in my Caddyfile to enable it? I don't know how I'd access this Ansible config within my server.

**Comment by mholt** [comment]
The Caddyfile configures Caddy, it does not configure your Linux system. It'll have to be enabled outside of Caddy. It has nothing to do with Caddy.

**Comment by NetOperatorWibby** [comment]
Ah got it. Unfortunate.

**Comment by mholt** [comment]
... do you want us to enable it? (You closed the issue, so I'm not sure if you've given up and there's nothing we need to do, or...)

**Comment by NetOperatorWibby** [comment]
I would like to have it enabled but it seemed like "that's just how it is, womp."

**Comment by Mohammed90** [comment]
> I would like to have it enabled but it seemed like "that's just how it is, womp."

Not really. In fact, we started discussing enabling it based on your issue immediately after my reply pointing out where the disablement comes from and how it can be changed. Part of the hardening approach is to minimize the unneeded functions enabled on the server to reduce the exposure area. If SFTP is something commonly needed (haven't had anyone else request it since we published the image, almost a year ago), we will consider enabling it.

**Comment by NetOperatorWibby** [comment]
Oh okay! I'm certainly not used to this kind of openness on projects that have been around for a bit. Sounds good.

**Comment by Mohammed90** [comment]
For now, the most minimal way to enable it is to add this line in the `/etc/ssh/sshd_config` file:
`Subsystem sftp internal-sftp`

Then restart the sshd service using `sudo systemctl restart sshd.service`. You can append [any of the flags listed here](https://manpages.debian.org/stretch/openssh-sftp-server/sftp-server.8.en.html) to `internal-sftp`. For example:
`Subsystem sftp internal-sftp -l INFO`

**Comment by NetOperatorWibby** [comment]
This works swimmingly, thanks!

**Comment by francislavoie** [comment]
This looks resolved. Closing.
