### ISSUE TITLE
Feature request: make configfile editable outside of the services file

### ISSUE THREAD

**Issue by hvisage** [caddyserver/dist#56]
Good day,

 I've create PR 55 https://github.com/caddyserver/dist/pull/55 as a possible solution/method to allow for a `/etc/default/caddy` file where you specify the configfile that caddy should use, instead of editing the systemd services' file.

**Comment by carlwgeorge** [comment]
Closing as we've discussed and declined in #55.

**Comment by francislavoie** [comment]
The right way is to use `systemctl edit` or systemd's built-in override mechanism: https://github.com/caddyserver/dist/pull/55#issuecomment-785167432
