### ISSUE TITLE
Add openSUSE Leap 15.3 build target to Copr

### ISSUE THREAD

**Issue by losuler** [caddyserver/dist#65]
openSUSE Leap 15.3 was released recently<sup>[[1]](https://news.opensuse.org/2021/06/02/opensuse-leap-bridges-path-to-enterprise/)</sup> so I was hoping the build target could be added to the Caddy Copr repo<sup>[[2]](https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/)</sup> so it will be compatible with openSUSE Leap 15.3.

<sup>[1]</sup> https://news.opensuse.org/2021/06/02/opensuse-leap-bridges-path-to-enterprise/
<sup>[2]</sup> https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/

**Comment by carlwgeorge** [comment]
I added Leap 15.3 in the settings for future builds, and tried to rebuild the latest build for it.  Unfortunately [it failed to initialize the chroot](https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/2225978/).  I don't know much about SUSE, that's @Conan-Kudo's thing.  Looks like he's tracking it over in https://github.com/rpm-software-management/mock/issues/731.

**Comment by Conan-Kudo** [comment]
This should be taken care of with the next mock-core-configs release, which will have my fix for this (https://github.com/rpm-software-management/mock/commit/32f0547afe5af3e35f9d911fe5e620017752384c).

**Comment by francislavoie** [comment]
So, looks like this is done @carlwgeorge @Conan-Kudo ?

**Comment by Conan-Kudo** [comment]
Actually, we hadn't done a build of Caddy until now! 😅

I'm setting up the Leap 15.3 build now.

**Comment by Conan-Kudo** [comment]
Leap 15.3 build of Caddy is now built: https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/2521311/

I have deactivated Leap 15.2 accordingly and updated the COPR page.
