### ISSUE TITLE
please add license

### ISSUE THREAD

**Issue by pymnh** [caddyserver/dist#67]
I am currently working on packaging Caddy for Debian. 
IMO a lot of this repo should be packaged together with Caddy, but in order to include them in Debian they need a (free) license.
Also, I would be glad not to have to write them myself 😉

**Comment by francislavoie** [comment]
Sure thing. #68

**Comment by pymnh** [comment]
> Sure thing.

Thanks

> Please keep us in the loop for the packaging efforts.

Sure :) 
I am tracking my work [here](https://salsa.debian.org/peymaneh/gsoc/-/issues?label_name%5B%5D=caddy), as one can see there is still some work to do but I'll ping you once its done
