### ISSUE TITLE
Please consider tagging dist repo in sync with caddy repo

### ISSUE THREAD

**Issue by pymnh** [caddyserver/dist#69]
It would be very helpful for Debian packaging if caddyserver/dist was tagged in sync with caddyserver/caddy.

Debian packages contain a watch-file that defines patterns, urls and transfer methods (ftp, https, git...) for fetching a specified or the latest version of upstream source code from one or more download locations. 

Right now, the watch file would define to download the release that matches $version of the Debian package on `https://github.com/caddyserver/caddy/tags`  and to fetch HEAD from `https://github.com/caddyserver/dist.git`. 
For untagged repos, $version is derived from the commit. divergent versions in one package are then being concatenated with `+~` in between. That means for Caddy that its Debian package would have version `2.4.3+~0.0~git20210810.d90cabd-1`. Might make sense for some packages, but for this case it would only cause a lot of confusion for Debian users (and annoyance for maintainers)

**Comment by francislavoie** [comment]
In case you missed it @pymnh, this should be resolved by #70. Short of it is when a release is published on the main https://github.com/caddyserver/caddy repo, it'll trigger an action on this repo which will tag the latest on the master branch with the same version number.

**Comment by pymnh** [comment]
awesome, thanks :)
