### ISSUE TITLE
Support init.d in apt repo

### ISSUE THREAD

**Issue by quaggalinux** [caddyserver/dist#71]
For example the NGINX will put a initial script "nginx" in /etc/init.d/ as part of apt install. 
Because the WSL v1 in windows does not have systemd, but WSL v1 can support service command and service command need the app to have initial script in /etc/init.d/ to use.

Thank you.

**Comment by francislavoie** [comment]
I don't use `init.d` (nor do I think most of the other maintainers) so we would need help to write them.

**Comment by francislavoie** [comment]
We haven't had any other interest for this or help to set it up, so I'll close this for now.
