### ISSUE TITLE
Add `--pidfile` to the systemd unit file in the official package

### ISSUE THREAD

**Issue by windware-ono** [caddyserver/dist#81]
`--pidfile` option was added through https://github.com/caddyserver/caddy/issues/3235 but the option can only be specified through command line parameter which is not easy to do without modifying the systemd unit file, which is not practical when it gets overridden on package updates.

Can you add `--pidfile /var/run/caddy.pid` in the systemd unit file in the official package?

**Comment by francislavoie** [comment]
FYI, you can easily add it to your systemd service by setting up an override. See here in the docs: https://caddyserver.com/docs/running#overrides

I don't feel equipped to make a decision about this right now, I'm not sure what the cons might be from making this change, whether it might impact any existing users negatively. So for now, probably best that you use the override as a workaround.

**Comment by windware-ono** [comment]
Thanks for letting me know about the overrides.

However,  adding the following block within the override gives a permission denied error, presumably because the unit file has the executing user defined as `caddy` (but how does it bind to port 80 from a local user?) and `/var/run` is only `root` writeable.

```
[Service]
ExecStart=
ExecStart=/usr/bin/caddy run --pidfile /var/run/caddy.pid --environ --config /etc/caddy/Caddyfile
```

and I went on to use `/tmp` as `--pidfile /tmp/caddy.pid` but this time, as [PrivateTmp](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=) is set to true for Caddy's systemd unit file, it's actually located in a unique ID prefixed directory created by systemd under `/tmp` and I've tried having [JoinsNamespaceOf](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#JoinsNamespaceOf=) with the following block in `monit`'s override but that doesn't seem to allow `monit` to read the `/tmp/caddy.pid` mentioned in monitoring definition files.

```
[Unit]
JoinsNamespaceOf=caddy.service
```

Putting a PID file in any other world writeable location sounds like a wrong practice but is there a proper way to handle reading the PID file from another process?

**Comment by francislavoie** [comment]
Systemd has its own `PIDFile=` option, but it notes that it should be avoided by modern projects. https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=

**Comment by windware-ono** [comment]
I'm not sure I understand the `PIDFile=` option in systemd's documentation as it seems it simply doesn't work unless `Type=forking`, and with the following override, it doesn't create the file no matter where I specify it.

(Relative path indicates under `/run`, `/tmp/caddy.pid` also doesn't work)
```
[Unit]
PIDFile=caddy.pid
```

It's probably tools like `monit` that needs to adapt to `systemd` as it's easy to get the PID with `systemctl show --property MainPID caddy`.

I'll go bug `monit` developers.
