### ISSUE TITLE
Use Built-in Manpage/Completion Commands

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/dist#82]
The current rpm and deb packaging specs rely on the [bit-rot completion scripts which used a tool called completely](https://github.com/caddyserver/dist/tree/f19b56d/scripts/completions). The PR caddyserver/caddy#4565 adds the benefit of adding 2 commands to generate manpages and completions scripts for {bash,fish,zsh}. Once the PR lands, the packaging specs should be updated to use the commands to generate fresh and accurate completion scripts and manpages.

**Comment by francislavoie** [comment]
I think this is done for `.deb` as of https://github.com/caddyserver/caddy/commit/aefd821ae0b966c8f8599eaa59dffe1b0fc51740

@carlwgeorge you might want to update your build scripts for COPR to include the man pages and bash completions?

**Comment by francislavoie** [comment]
This is done in https://github.com/caddyserver/dist/commit/e06ce615e2da93a5908ca9978a1f992b6fbe2ab5 for `.rpm` :tada:
