### ISSUE TITLE
Release 2.6.2 to copr.

### ISSUE THREAD

**Issue by fahrradflucht** [caddyserver/dist#90]
Hey it would be great if someone could ship the latest Caddy version to Copr. Besides other bugs, in the current Copr version (2.6.1) certs don't renew if people don't have an issuer set explicitly, which is a pretty big gotcha if people upgrade 😬.

**Comment by francislavoie** [comment]
This is handled by @carlwgeorge and @Conan-Kudo.

**Comment by carlwgeorge** [comment]
Thanks for the heads up.  I updated the copr to version 2.6.2.

https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/5019565/

**Comment by mholt** [comment]
Thank you Carl!! Really appreciate all you do 😊
