### ISSUE TITLE
ubuntu package providing `httpd` (like nginx, apache and lighttpd)

### ISSUE THREAD

**Issue by andreasnuesslein** [caddyserver/dist#91]
I was wondering if it was possible to add a "provides: nginx" or something like this to the caddy ubuntu packages?

Some packages require something like this:
```
$ apt-cache depends zammad
zammad
  ...
  Depends: curl
    curl:i386
 |Depends: elasticsearch
  Depends: <elasticsearch-oss>
 |Depends: nginx
    nginx-core
    nginx-extras
    nginx-full
    nginx-light
  Depends: apache2
 |Depends: postgresql
  ...
```

obviously the better solution would be to ask `zammad` to add `|Depends: caddy` to that block, but a) they have like >400 open issues on github, so I think that'd take longer and b) there might be other packages out there that would need that update too.

cheers :wave:

**Comment by andreasnuesslein** [comment]
> Fedora handles this by having all webserver packages provide the generic name "webserver", which other packages can depend on if they don't need to specify a particular webserver.

I totally agree that _many_ of the debian-packaging decisions are rather questionable. And I remember Gentoo having some waaay nicer foundations for their packages-logic. But still we live in a world where debian/ubuntu is quite predominant and I doubt that we can petition them to change their logic with this anytime soon :S

**Comment by francislavoie** [comment]
I'll close this, I don't think this particularly makes sense for us.

**Comment by endelwar** [comment]
Hi everyone,

Could we reopen this issue to consider adding Provides: httpd to Caddy's Debian package? Since httpd is a virtual package, this addition would improve compatibility with packages and scripts that depend on a generic HTTP server, allowing Caddy to serve as a drop-in alternative to Apache or Nginx in more contexts.

Including Provides: httpd would:

    Increase flexibility for system administrators choosing Caddy.
    Align with Debian packaging standards followed by other web servers.

Thanks for considering this; I think it could enhance Caddy's integration on Debian-based systems.

**Comment by francislavoie** [comment]
@endelwar you can easily add this yourself to your own systemd config with an override. See https://caddyserver.com/docs/running#overrides

**Comment by endelwar** [comment]
@francislavoie editing the systemd config doesn’t inform `apt` that a web server is already available on the system and that installing another one is unnecessary. In the Debian ecosystem, `httpd` ≠ `apache`. `httpd` is actually a virtual package ([Debian's httpd package](https://packages.debian.org/sid/httpd)), which allows `apt` to recognize that a compatible web server is installed.

By including `Provides: httpd` in Caddy's Debian package, it would prevent `apt` from automatically installing another web server (typically Apache2 on Debian) when a package declares a dependency on `httpd`. This change doesn’t make Caddy "pretend" to be Apache; rather, it allows Caddy to be recognized as a viable HTTP server option within the Debian package management system.

**Comment by francislavoie** [comment]
Oh sorry, got the apt config confused with systemd config, didn't re-read the whole thread this morning when this popped up on my phone, half awake.

I think our opinion still stands that Debian's approach is stupid, but whatever, should be simple enough: https://github.com/caddyserver/caddy/pull/6691

**Comment by endelwar** [comment]
Thank you all!

**Comment by andreasnuesslein** [comment]
thanks @endelwar , that's exacly what i was thinking. i guess i never communited my point well enough 🙈
